# its used for run the embedded server like tomcat.
server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bankapplication
    username: root
    password: root
    driver-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect

